### ISSUE TITLE
マイクロスレッド(コルーチン)を実装したい

### ISSUE THREAD

**Issue by Dan344** [Dan344/SampleStg-MonoGame#4]
イテレータ構文使う
よくわからない

**Comment by Dan344** [comment]
69128da44531b388af3f7531a3801e5b4c14eb79

一応実装したけど、なんとなく使い方も分かったし、各オブジェクトが好きに持てばよいかも

**Comment by Dan344** [comment]
解決した

**Comment by ncaq** [comment]
え,なんでこれ自作してるんですか?

**Comment by Dan344** [comment]
どういう意味かよくわからないので詳しく 💦

**Comment by ncaq** [comment]
すみません,ちょっとC# について知識不足なので調べてみます

**Comment by Dan344** [comment]
いや、こちらも詳しくはないのでなんとも…

実装した内容は、Coroutineそのものを作った訳ではなく、単にCoroutineを楽に動かせる静的なメソッドを用意したというだけです。Coroutineの仕組み自体は、確かにC#のイテレータ構文で使えますね。

**Comment by ncaq** [comment]
だから少なくとも名前が`Coroutine`なのはなんか不自然な気がしたんですよね,コルーチンを実装したというのもヘン,何やってるコードなのかC# がわからんので解読してませんけど

**Comment by Dan344** [comment]
まぁ、C#にCoroutineクラスがあるわけではない(多分)ので、自分としてはそんなに違和感ないですね。あるいは、どっかの基底クラスに置いとくのが良いのかもしれないけど(UnityのCoroutineはそんな感じ : MonoBehaviors)。

というか、commitとissueが紐付いてなかった 05a242c7233e33578b49125e877688aff9eee0dd という感じになっています。

やってる事はシンプルで、呼び出し元にある `IEnumerator` の参照と処理を渡して、毎フレーム呼べばCoroutineとして動くというだけです。

**Comment by Dan344** [comment]
まぁ、もっと良い実装もありそうなのでプルリク下さい
